/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DiaLogItem: typeof import('./src/components/dialog/DiaLogItem.vue')['default']
    DiaLogWrapper: typeof import('./src/components/dialog/DiaLogWrapper.vue')['default']
    ElInput: typeof import('element-plus/es')['ElInput']
    Main: typeof import('./src/components/Main.vue')['default']
    Prompt: typeof import('./src/components/Prompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
}
